- name: Configure static CV webserver
  hosts: cv_static_server
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: present
      update_cache: true

  - name: Disable UFW # we already have AWS NACL and SGs, so this is not necessary
    community.general.ufw:
      state: disabled

  - name: Enable NGINX service
    systemd:
      name: nginx
      enabled: true

  - name: Delete exisiting .html files
    file:
      state: absent
      path: /var/www/html/

  - name: Copy static web files to remote
    copy:
      src: ../static-cv/
      dest: /var/www/html

  - name: Remove default site available
    file: 
      state: absent
      path: /etc/nginx/sites-available/default

  - name: Remove default site enabled
    file: 
      state: absent
      path: /etc/nginx/sites-enabled/default

  - name: Copy nginx config to remote
    copy: 
      src: ../nginx/nginx.conf
      dest: /etc/nginx/

  - name: Add new CV sites
    copy: 
      src: ../nginx/static-cv
      dest: /etc/nginx/sites-available/

  - name: Symlink CV site to enabled sites
    file: 
      src: /etc/nginx/sites-available/static-cv
      dest: /etc/nginx/sites-enabled/static-cv
      state: link


  # #### Certbot config
  # - name: Install snapd
  #   apt:
  #     name: snapd
  #     state: present

  # - name: Ensure snapd is up to date
  #   community.general.snap:
  #     name: core 
  #     state: present
  
  # - name: Install certbot
  #   community.general.snap:
  #     name: certbot  
  #     state: present
  #     classic: true

  # - name: Prepare certbot command
  #   file: 
  #     src: /snap/bin/certbot
  #     dest: /usr/bin/certbot
  #     state: link

  # - name: Get and install certificate
  #   ansible.builtin.command:
  #     cmd: certbot --nginx
    
  - name: Reload NGINX service
    systemd:
      name: nginx
      state: restarted
  

